[project]
name = "cooking-compass-image"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sukin Raj", email = "sukinraj332005@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.83",
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.52.4",
]

[project.scripts]
cooking-compass-image = "cooking_compass_image:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
